{$ include 'pygfx.std.wgsl' $}
{$ include 'pygfx.colormap.wgsl' $}
{$ include 'pygfx.image_sample.wgsl' $}
{$ include 'pygfx.light_phong_simple.wgsl' $}
// NOTE: do NOT include 'pygfx.volume_common.wgsl' — we bypass get_vol_geometry().

// ── Constants ──────────────────────────────────────────────────────────────
const BORDER: f32          = 1.0;     // ghost border width in voxels
const MAX_BRICK_ITERS: u32 = 512u;   // outer loop guard
const STEPS_PER_BRICK: f32 = 24.0;   // target inner steps across a full brick

// Varyings are auto-generated by pygfx's VaryingResolver from assignments
// in vs_main. Do NOT define a struct Varyings here.


// ── Block-scale lookup ────────────────────────────────────────────────────
// u_block_scales.scale_k = downscale factor relative to finest level.
// k=0 always [1,1,1]. k=1 might be [2,2,2] (isotropic) or [1,1,2] (z-only).
// The w channel of the LUT stores level index (1-based: 0 = unloaded).
fn get_lod_scale(lut_w: u32) -> vec3<f32> {
    // lut_w is 1-based (0 = unloaded). scale_k is stored at index k in Python.
    // lut_w=1 (finest) → scale_1, lut_w=2 → scale_2, etc.
    switch lut_w {
        case 1u:  { return u_block_scales.scale_1.xyz; }
        case 2u:  { return u_block_scales.scale_2.xyz; }
        case 3u:  { return u_block_scales.scale_3.xyz; }
        case 4u:  { return u_block_scales.scale_4.xyz; }
        case 5u:  { return u_block_scales.scale_5.xyz; }
        case 6u:  { return u_block_scales.scale_6.xyz; }
        case 7u:  { return u_block_scales.scale_7.xyz; }
        case 8u:  { return u_block_scales.scale_8.xyz; }
        case 9u:  { return u_block_scales.scale_9.xyz; }
        default:  { return u_block_scales.scale_1.xyz; }
    }
}


// ── LOD debug colour ──────────────────────────────────────────────────────
fn get_lod_color(lut_w: u32) -> vec3<f32> {
    switch lut_w {
        case 0u:  { return vec3<f32>(0.0, 0.0, 0.0); }   // unloaded
        case 1u:  { return vec3<f32>(0.0, 1.0, 0.0); }   // finest — green
        case 2u:  { return vec3<f32>(0.5, 1.0, 0.0); }   // yellow-green
        case 3u:  { return vec3<f32>(1.0, 1.0, 0.0); }   // yellow
        case 4u:  { return vec3<f32>(1.0, 0.5, 0.0); }   // orange
        case 5u:  { return vec3<f32>(1.0, 0.0, 0.0); }   // red
        default:  { return vec3<f32>(0.5, 0.0, 0.5); }   // purple
    }
}


// ── Coordinate conversions ────────────────────────────────────────────────

// Normalized space → finest-level voxel space.
// Normalized box: [-normalizedSize/2, +normalizedSize/2]
// Voxel box:      [0, datasetSize)
fn norm_to_voxel(pos: vec3<f32>, norm_size: vec3<f32>, dataset_size: vec3<f32>) -> vec3<f32> {
    return ((pos / norm_size) + 0.5) * dataset_size;
}

fn voxel_to_norm(voxel: vec3<f32>, norm_size: vec3<f32>, dataset_size: vec3<f32>) -> vec3<f32> {
    return (voxel / dataset_size - 0.5) * norm_size;
}


// ── Ray-box intersection ──────────────────────────────────────────────────

// Standard slab test. Returns vec2(tNear, tFar).
// tNear > tFar means miss.
fn intersect_box(
    ray_origin: vec3<f32>, inv_ray_dir: vec3<f32>,
    box_min: vec3<f32>,   box_max: vec3<f32>
) -> vec2<f32> {
    let t0 = (box_min - ray_origin) * inv_ray_dir;
    let t1 = (box_max - ray_origin) * inv_ray_dir;
    let t_near = max(max(min(t0.x, t1.x), min(t0.y, t1.y)), min(t0.z, t1.z));
    let t_far  = min(min(max(t0.x, t1.x), max(t0.y, t1.y)), max(t0.z, t1.z));
    return vec2<f32>(t_near, t_far);
}


// ── Random / hash utilities ───────────────────────────────────────────────

fn hash(n: u32) -> u32 {
    var x = n;
    x = ((x >> 16u) ^ x) * 0x45d9f3bu;
    x = ((x >> 16u) ^ x) * 0x45d9f3bu;
    x = (x >> 16u) ^ x;
    return x;
}

fn rand(seed: u32) -> f32 {
    return f32(hash(seed)) / f32(0xffffffffu);
}

fn ray_to_seed(ray_dir: vec3<f32>) -> u32 {
    let x = u32((ray_dir.x + 1.0) * 32768.0);
    let y = u32((ray_dir.y + 1.0) * 32768.0);
    let z = u32((ray_dir.z + 1.0) * 32768.0);
    return x + y * 65536u + z * 17u;
}


// ── Atlas sampling (nearest-neighbour) ────────────────────────────────────

fn sample_atlas_nearest(
    voxel_pos:  vec3<f32>,   // finest-level voxel coordinates
    lut_entry:  vec4<u32>,   // RGB = slot indices, W = lut_w (level, 1-based)
    lod_scale:  vec3<f32>,   // downscale factor for this level
) -> f32 {
    let block_size  = vec3<f32>(u_vol_params.block_size_x,
                                u_vol_params.block_size_y,
                                u_vol_params.block_size_z);
    let cache_size  = vec3<f32>(u_vol_params.cache_size_x,
                                u_vol_params.cache_size_y,
                                u_vol_params.cache_size_z);
    let padded_size = block_size + vec3<f32>(2.0 * BORDER);

    // Atlas slot base (in texels).
    let tile_origin = vec3<f32>(lut_entry.xyz) * padded_size;

    // Map finest-level voxel → level-k voxel, then take modulo block.
    let voxel_k     = voxel_pos / lod_scale;            // element-wise divide
    let pos_in_brick = voxel_k - floor(voxel_k / block_size) * block_size;

    // + BORDER: skip ghost border.  + 0.5: sample voxel centre.
    let cache_pos   = tile_origin + pos_in_brick + vec3<f32>(BORDER + 0.5);
    let cache_coord = cache_pos / cache_size;

    return textureSample(t_cache, s_cache, cache_coord).r;
}


// ── Brick setup ───────────────────────────────────────────────────────────

struct BrickInfo {
    lut_entry: vec4<u32>,
    lod_scale: vec3<f32>,
    t_end:     f32,
    num_steps: u32,
    step_size: f32,
    valid:     bool,
};

fn setup_brick(
    ray_origin:  vec3<f32>,
    ray_dir:     vec3<f32>,
    inv_ray_dir: vec3<f32>,
    t:           f32,
    t_end_ray:   f32,
    norm_size:   vec3<f32>,
    dataset_size: vec3<f32>,
) -> BrickInfo {
    var info: BrickInfo;

    let block_size = vec3<f32>(u_vol_params.block_size_x,
                               u_vol_params.block_size_y,
                               u_vol_params.block_size_z);
    let lut_size_i = vec3<i32>(i32(u_vol_params.lut_size_x),
                               i32(u_vol_params.lut_size_y),
                               i32(u_vol_params.lut_size_z));

    // 1. Current ray position → finest-level voxel → brick index.
    let sample_pos = ray_origin + ray_dir * t;
    let voxel_pos  = clamp(
        norm_to_voxel(sample_pos, norm_size, dataset_size),
        vec3<f32>(0.0),
        dataset_size - vec3<f32>(0.001)
    );
    let brick_f   = floor(voxel_pos / block_size);
    let safe_idx  = clamp(vec3<i32>(brick_f),
                          vec3<i32>(0),
                          lut_size_i - vec3<i32>(1));

    // 2. Brick AABB in normalized space.
    let brick_min_v = brick_f * block_size;
    let brick_max_v = brick_min_v + block_size;
    let brick_min_n = voxel_to_norm(brick_min_v, norm_size, dataset_size);
    let brick_max_n = voxel_to_norm(brick_max_v, norm_size, dataset_size);

    // 3. Ray exits at min(brick tFar, ray tEnd).
    let t_brick    = intersect_box(ray_origin, inv_ray_dir, brick_min_n, brick_max_n);
    info.t_end     = min(t_brick.y, t_end_ray);

    // 4. LUT lookup.
    let lut_entry  = textureLoad(t_lut, safe_idx, 0);
    info.lut_entry = lut_entry;
    info.valid     = lut_entry.w > 0u;   // w==0 → not yet loaded

    // 5. If valid, compute step budget.
    if (info.valid) {
        info.lod_scale = get_lod_scale(lut_entry.w);
        let brick_len       = max(info.t_end - t, 1e-6);
        let brick_world_len = length(brick_max_n - brick_min_n);
        info.num_steps = max(1u, u32(STEPS_PER_BRICK * brick_len / brick_world_len));
        info.step_size = brick_len / f32(info.num_steps);
    }

    return info;
}


// ── Vertex shader ─────────────────────────────────────────────────────────

struct VertexInput {
    @builtin(vertex_index) vertex_index: u32,
};

@vertex
fn vs_main(in: VertexInput) -> Varyings {
    let ns = vec3<f32>(u_vol_params.norm_size_x,
                       u_vol_params.norm_size_y,
                       u_vol_params.norm_size_z);
    let h = ns * 0.5;

    // 8 corners of the normalized box.
    let corners = array<vec3<f32>, 8>(
        vec3<f32>(-h.x, -h.y, -h.z),
        vec3<f32>( h.x, -h.y, -h.z),
        vec3<f32>(-h.x,  h.y, -h.z),
        vec3<f32>( h.x,  h.y, -h.z),
        vec3<f32>(-h.x, -h.y,  h.z),
        vec3<f32>( h.x, -h.y,  h.z),
        vec3<f32>(-h.x,  h.y,  h.z),
        vec3<f32>( h.x,  h.y,  h.z),
    );

    // 12 triangles (36 indices), cull_mode = none.
    let indices = array<u32, 36>(
        0u,2u,1u, 1u,2u,3u,   // -Z face
        4u,5u,6u, 5u,7u,6u,   // +Z face
        0u,1u,4u, 1u,5u,4u,   // -Y face
        2u,6u,3u, 3u,6u,7u,   // +Y face
        0u,4u,2u, 2u,4u,6u,   // -X face
        1u,3u,5u, 3u,7u,5u,   // +X face
    );

    let norm_pos  = corners[indices[in.vertex_index]];
    let world_pos = u_wobject.world_transform * vec4<f32>(norm_pos, 1.0);
    let ndc_pos   = u_stdinfo.projection_transform
                  * u_stdinfo.cam_transform
                  * world_pos;

    let ndc_to_norm = u_wobject.world_transform_inv
                    * u_stdinfo.cam_transform_inv
                    * u_stdinfo.projection_transform_inv;

    let cam_sign = sign(
        u_stdinfo.cam_transform[0][0] *
        u_stdinfo.cam_transform[1][1] *
        u_stdinfo.cam_transform[2][2]
    );

    var varyings: Varyings;
    varyings.position      = vec4<f32>(ndc_pos);
    varyings.world_pos     = vec3<f32>(world_pos.xyz);
    varyings.norm_near_pos = vec4<f32>(ndc_to_norm * vec4<f32>(ndc_pos.xy, -1.0 * cam_sign * ndc_pos.w, ndc_pos.w));
    varyings.norm_far_pos  = vec4<f32>(ndc_to_norm * vec4<f32>(ndc_pos.xy,        cam_sign * ndc_pos.w, ndc_pos.w));
    return varyings;
}


// ── Fragment shader ───────────────────────────────────────────────────────

@fragment
fn fs_main(varyings: Varyings) -> FragmentOutput {
    {$ include 'pygfx.clipping_planes.wgsl' $}

    var out: FragmentOutput;

    let norm_size    = vec3<f32>(u_vol_params.norm_size_x,
                                 u_vol_params.norm_size_y,
                                 u_vol_params.norm_size_z);
    let dataset_size = vec3<f32>(u_vol_params.dataset_size_x,
                                 u_vol_params.dataset_size_y,
                                 u_vol_params.dataset_size_z);
    let iso_threshold = u_material.threshold;
    let frame_index   = u_vol_params.frame_index;

    // ── Ray setup in normalized space ──────────────────────────────────
    let far_pos  = varyings.norm_far_pos.xyz  / varyings.norm_far_pos.w;
    let near_pos = varyings.norm_near_pos.xyz / varyings.norm_near_pos.w;
    let ray_dir  = normalize(far_pos - near_pos);

    // Guard near-zero components to avoid NaN downstream.
    let safe_dir    = select(ray_dir, vec3<f32>(1e-10), abs(ray_dir) < vec3<f32>(1e-10));
    let inv_ray_dir = 1.0 / safe_dir;

    // ── Volume AABB intersection from the near plane ───────────────────
    // Using near_pos (not the box surface) as origin means tNear < 0 when
    // the camera is inside the volume, and max(tNear, 0) clamps to the
    // near plane — correct for both inside and outside cases.
    let half_ns = norm_size * 0.5;
    let hit     = intersect_box(near_pos, inv_ray_dir, -half_ns, half_ns);
    if (hit.x > hit.y) { discard; }

    var t_start = max(hit.x, 0.0);
    let t_end   = hit.y;
    if (t_start >= t_end) { discard; }

    $$ if debug_mode == 'ray_dir'
    // ── Debug: show ray direction as RGB ──────────────────────────────
    out.color = vec4<f32>((ray_dir + 1.0) * 0.5, 1.0);
    out.depth = 0.0;

    $$ else
    // ── Brick traversal ────────────────────────────────────────────────
    // All state variables are declared unconditionally (Metal does not
    // allow variable redefinition across template branches).
    let ray_origin    = near_pos;
    let ray_seed_base = ray_to_seed(ray_dir);

    var t             = t_start;

    // ISO state
    var surface_found = false;
    var surface_pos:  vec3<f32>;
    var surface_density: f32 = 0.0;
    var prev_density: f32 = 0.0;
    var prev_t: f32 = t_start;
    var surface_lut_entry: vec4<u32>;
    var surface_lod_scale: vec3<f32>;
    var surface_step_size: f32 = 0.0;

    // MIP state
    var max_density: f32 = 0.0;

    // LOD debug state (always declared; only used in lod_color mode)
    var lod_debug_color = vec3<f32>(0.0);
    var lod_debug_found = false;

    for (var brick_iter = 0u; brick_iter < MAX_BRICK_ITERS; brick_iter++) {
        $$ if render_mode == 'mip'
        if (t >= t_end) { break; }
        $$ else
        if (t >= t_end || surface_found) { break; }
        $$ endif

        let brick = setup_brick(ray_origin, ray_dir, inv_ray_dir,
                                t, t_end, norm_size, dataset_size);

        $$ if debug_mode == 'lod_color'
        if (brick.valid && !lod_debug_found) {
            lod_debug_color = get_lod_color(brick.lut_entry.w);
            lod_debug_found = true;
            break;
        }
        $$ endif

        if (!brick.valid) {
            t = brick.t_end + 0.0001;
            prev_density = 0.0;
            continue;
        }

        // Capture for post-loop bisection (ISO only, but always written).
        surface_lut_entry = brick.lut_entry;
        surface_lod_scale = brick.lod_scale;
        surface_step_size = brick.step_size;

        // Per-brick stochastic jitter — re-seeds at every brick crossing.
        let jitter   = rand(ray_seed_base + brick_iter + frame_index) * brick.step_size;
        var t_sample = t + jitter;

        for (var i = 0u; i < brick.num_steps; i++) {
            if (t_sample > brick.t_end) { break; }

            let pos     = ray_origin + ray_dir * t_sample;
            let voxel   = norm_to_voxel(pos, norm_size, dataset_size);
            let density = sample_atlas_nearest(voxel, brick.lut_entry, brick.lod_scale);

            $$ if render_mode == 'mip'
            // MIP: track maximum intensity across the entire ray.
            max_density = max(max_density, density);
            $$ else
            // ISO: detect threshold crossing.
            if (prev_density < iso_threshold && density >= iso_threshold) {
                surface_found   = true;
                surface_pos     = pos;
                surface_density = density;
                break;
            }
            prev_density = density;
            prev_t       = t_sample;
            $$ endif

            t_sample += brick.step_size;
        }

        $$ if render_mode != 'mip'
        if (!surface_found) {
            t = brick.t_end + 0.0001;
        }
        $$ else
        t = brick.t_end + 0.0001;
        $$ endif
    }

    // ── Post-traversal output ─────────────────────────────────────────

    $$ if debug_mode == 'lod_color'
    if (!lod_debug_found) { discard; }
    out.color = vec4<f32>(lod_debug_color, 1.0);
    out.depth = 0.0;

    $$ elif render_mode == 'mip'
    // ── MIP output ────────────────────────────────────────────────────
    if (max_density <= 0.0) { discard; }

    let mip_value = vec4<f32>(max_density, 0.0, 0.0, 1.0);
    let mip_color = sampled_value_to_color(mip_value);
    $$ if colorspace == 'srgb'
    let mip_physical = srgb2physical(mip_color.rgb);
    $$ else
    let mip_physical = mip_color.rgb;
    $$ endif

    let mip_opacity = mip_color.a * u_material.opacity;
    do_alpha_test(mip_opacity);

    out.color = vec4<f32>(mip_physical, mip_opacity);
    out.depth = 0.0;

    $$ else
    // ── ISO output ────────────────────────────────────────────────────
    if (!surface_found) { discard; }

    // ── Binary bisection refinement (4 iterations → 16× finer) ────────
    var lo = prev_t;
    var hi = prev_t + surface_step_size;
    for (var r = 0u; r < 4u; r++) {
        let mid      = (lo + hi) * 0.5;
        let pos_mid  = ray_origin + ray_dir * mid;
        let voxel_m  = norm_to_voxel(pos_mid, norm_size, dataset_size);
        let d_mid    = sample_atlas_nearest(voxel_m, surface_lut_entry, surface_lod_scale);
        if (d_mid >= iso_threshold) { hi = mid; } else { lo = mid; }
    }
    let refined_t   = (lo + hi) * 0.5;
    let refined_pos = ray_origin + ray_dir * refined_t;

    // ── Gradient-based normal (central differences in voxel space) ────
    // Offset by ~1.5 voxels at the current LOD level (in finest-level coords).
    let grad_eps    = surface_lod_scale * 1.5;
    let refined_v   = norm_to_voxel(refined_pos, norm_size, dataset_size);
    let dx = sample_atlas_nearest(refined_v + vec3<f32>(grad_eps.x, 0.0, 0.0),
                                  surface_lut_entry, surface_lod_scale)
           - sample_atlas_nearest(refined_v - vec3<f32>(grad_eps.x, 0.0, 0.0),
                                  surface_lut_entry, surface_lod_scale);
    let dy = sample_atlas_nearest(refined_v + vec3<f32>(0.0, grad_eps.y, 0.0),
                                  surface_lut_entry, surface_lod_scale)
           - sample_atlas_nearest(refined_v - vec3<f32>(0.0, grad_eps.y, 0.0),
                                  surface_lut_entry, surface_lod_scale);
    let dz = sample_atlas_nearest(refined_v + vec3<f32>(0.0, 0.0, grad_eps.z),
                                  surface_lut_entry, surface_lod_scale)
           - sample_atlas_nearest(refined_v - vec3<f32>(0.0, 0.0, grad_eps.z),
                                  surface_lut_entry, surface_lod_scale);
    let gradient = vec3<f32>(dx, dy, dz);
    let normal   = select(normalize(-gradient), vec3<f32>(0.0, 1.0, 0.0),
                          length(gradient) < 1e-6);

    $$ if debug_mode == 'normal_rgb'
    // ── Debug: normal as RGB ───────────────────────────────────────────
    out.color = vec4<f32>((normal + 1.0) * 0.5, 1.0);
    out.depth = 0.0;

    $$ else
    // ── Phong shading ──────────────────────────────────────────────────
    let the_value      = vec4<f32>(surface_density, 0.0, 0.0, 1.0);
    let color          = sampled_value_to_color(the_value);
    $$ if colorspace == 'srgb'
    let physical_color = srgb2physical(color.rgb);
    $$ else
    let physical_color = color.rgb;
    $$ endif

    let view_dir   = normalize(-ray_dir);
    let is_front   = dot(normal, view_dir) > 0.0;
    let lit_color  = lighting_phong(is_front, normal, view_dir, physical_color);

    let opacity = color.a * u_material.opacity;
    do_alpha_test(opacity);

    // ── Depth output ───────────────────────────────────────────────────
    let world_pos_r = u_wobject.world_transform * vec4<f32>(refined_pos, 1.0);
    let ndc_pos_r   = u_stdinfo.projection_transform
                    * u_stdinfo.cam_transform
                    * world_pos_r;

    out.color = vec4<f32>(lit_color, opacity);
    out.depth = ndc_pos_r.z / ndc_pos_r.w;
    $$ endif
    $$ endif
    $$ endif

    return out;
}
